name: Release
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install libusb
        run: sudo apt install libusb-1.0-0-dev
      - uses: actions/checkout@v3
      - uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-flags: '-l -d'
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - uses: golangci/golangci-lint-action@v3
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Install libusb
        run: sudo apt install libusb-1.0-0-dev
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - run: go test -v ./...
  release:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - name: Install libusb
        run: sudo apt install libusb-1.0-0-dev
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - uses: go-semantic-release/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
